version: "3"

services:
  # content:
  #   build:
  #     context: .
  #     dockerfile: "content.Dockerfile"
  #   command: "sh /bootstrap.sh"
  cache:
    build:
      context: .
      dockerfile: "cache.Dockerfile"
    command: "sh /bootstrap.sh"
    networks:
      app_net:
        ipv4_address: "172.16.238.10"

networks:
  app_net:
    driver: bridge
    ipam:
      config:
      - subnet: '172.16.238.0/24'
